---
- name: Install MySQL
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Set MySQL root password
  ansible.builtin.mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes
    column_case_sensitive: false
