---
- name: inventory collections
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  vars_files:
    - vars/main.yaml
  roles:
    - ping
    - networking
    - utilization
    - users
